### ISSUE TITLE
换了主题之后，hexo g 报错

### ISSUE THREAD

**Issue by urzz** [cccyb/hexo-theme-pinghsu#1]
```
ERROR /Users/urzz/Project/own/other/blog/themes/pinghsu/layout/tag.ejs:8
    6| <%- partial('_partial/page-archive') %>
    7|
 >> 8| <%- partial('_partial/footer') %>

/Users/urzz/Project/own/other/blog/themes/pinghsu/layout/_partial/footer.ejs:26
    24|                     	<p>Theme is <a href="https://github.com/cccyb/hexo-theme-pinghsu" target="_blank">Pinghsu</a> by <a href="<%= config.url %>" target="_blank"><%= config.author %></a></p>
    25| 						<p>Powered by <a href="https://hexo.io/" target="_blank" rel="nofollow">hexo</a></p>
 >> 26|                         <p style="margin-top: 10px">站点总字数：<%= totalcount(site) %></p>
    27|                         <% if (theme.busuanzi) { %>
    28|                         <p><span id="busuanzi_container_site_pv" style='display:none'><%- __('views.text') %> <span id="busuanzi_value_site_pv"></span> <%- __('views.unit') %></span></p>
    29|                         <p><span id="busuanzi_container_site_uv" style='display:none'><%- __('vistors.text') %> <span id="busuanzi_value_site_uv"></span> <%- __('vistors.unit') %></span></p>

totalcount is not defined
ReferenceError: /Users/urzz/Project/own/other/blog/themes/pinghsu/layout/tag.ejs:8
    6| <%- partial('_partial/page-archive') %>
    7|
 >> 8| <%- partial('_partial/footer') %>

/Users/urzz/Project/own/other/blog/themes/pinghsu/layout/_partial/footer.ejs:26
    24|                     	<p>Theme is <a href="https://github.com/cccyb/hexo-theme-pinghsu" target="_blank">Pinghsu</a> by <a href="<%= config.url %>" target="_blank"><%= config.author %></a></p>
    25| 						<p>Powered by <a href="https://hexo.io/" target="_blank" rel="nofollow">hexo</a></p>
 >> 26|                         <p style="margin-top: 10px">站点总字数：<%= totalcount(site) %></p>
    27|                         <% if (theme.busuanzi) { %>
    28|                         <p><span id="busuanzi_container_site_pv" style='display:none'><%- __('views.text') %> <span id="busuanzi_value_site_pv"></span> <%- __('views.unit') %></span></p>
    29|                         <p><span id="busuanzi_container_site_uv" style='display:none'><%- __('vistors.text') %> <span id="busuanzi_value_site_uv"></span> <%- __('vistors.unit') %></span></p>

totalcount is not defined
    at eval (eval at exports.compile (/Users/urzz/Project/own/other/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1728)
    at eval (eval at exports.compile (/Users/urzz/Project/own/other/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:16456)
    at /Users/urzz/Project/own/other/blog/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiledSync.locals [as _compiledSync] (/Users/urzz/Project/own/other/blog/node_modules/hexo/lib/theme/view.js:120:22)
    at Theme._View.View.View.renderSync (/Users/urzz/Project/own/other/blog/node_modules/hexo/lib/theme/view.js:48:23)
    at Object.partial (/Users/urzz/Project/own/other/blog/node_modules/hexo/lib/plugins/helper/partial.js:39:15)
    at Object.wrapper [as partial] (/Users/urzz/Project/own/other/blog/node_modules/lodash/lodash.js:4949:19)
    at eval (eval at exports.compile (/Users/urzz/Project/own/other/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:33:99)
    at eval (eval at exports.compile (/Users/urzz/Project/own/other/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:33:136)
    at /Users/urzz/Project/own/other/blog/node_modules/ejs/lib/ejs.js:255:15
    at Theme._View.View._compiled.locals [as _compiled] (/Users/urzz/Project/own/other/blog/node_modules/hexo/lib/theme/view.js:124:48)
    at Theme._View.View.View.render (/Users/urzz/Project/own/other/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at route.set (/Users/urzz/Project/own/other/blog/node_modules/hexo/lib/hexo/index.js:386:29)
    at tryCatcher (/Users/urzz/Project/own/other/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/urzz/Project/own/other/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/urzz/Project/own/other/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:442:10)
    at resume_ (_stream_readable.js:822:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by urzz** [comment]
看了眼文档发现是少了这个：
`npm i hexo-wordcount --save`

已解决了。。
